In [1]:
#1次元配列
import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [2]:
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [11]:
#2次元配列
b = np.array([[1,2,3],[4,5,6]])

b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [14]:
#reshape
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [19]:
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
c3 = c2.ravel()

c3

array([0, 1, 2, 3, 4, 5])

In [25]:
c4 = c2.flatten()

In [26]:
c4

array([0, 1, 2, 3, 4, 5])

In [27]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
a.dtype

dtype('int32')

In [30]:
d = np.array([1,2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [31]:
d.dtype

dtype('int16')

In [32]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [33]:
a

array([1, 2, 3])

In [34]:
a[0]

1

In [35]:
a[1:]

array([2, 3])

In [36]:
a[-1]

3

In [37]:
a[-1:]

array([3])

In [38]:
a[-2]

2

In [39]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b[0]

array([1, 2, 3])

In [41]:
b[1,0]

4

In [42]:
b[:,2]

array([3, 6])

In [43]:
b[1,:]

array([4, 5, 6])

In [44]:
b[0,1:]

array([2, 3])

In [45]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [46]:

a

array([1, 2, 3])

In [47]:
a[2]=4
a

array([1, 2, 4])

In [48]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
b[1,2]=7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [51]:
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [52]:
a1 = a
a1

array([1, 2, 4])

In [53]:
a1[1] = 5
a1

array([1, 5, 4])

In [54]:
a

array([1, 5, 4])

In [55]:
a2 = a.copy()
a2

array([1, 5, 4])

In [56]:
a2[0]=6
a2

array([6, 5, 4])

In [57]:
a

array([1, 5, 4])

In [58]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0]=6
c4[1]=7

In [60]:
c3

array([6, 1, 2, 3, 4, 5])

In [61]:
c4

array([0, 7, 2, 3, 4, 5])

In [62]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [63]:
c5 =c2.reshape(3,2)
c5

array([[6, 1],
       [2, 3],
       [4, 5]])

In [64]:
c5[0] =1
c5
c2

array([[1, 1, 2],
       [3, 4, 5]])

In [65]:
c2

array([[1, 1, 2],
       [3, 4, 5]])

In [66]:
c5

array([[1, 1],
       [2, 3],
       [4, 5]])

In [67]:
c2[0]=6

In [68]:
c2

array([[6, 6, 6],
       [3, 4, 5]])

In [69]:
c5

array([[6, 6],
       [6, 3],
       [4, 5]])

In [70]:
c4

array([0, 7, 2, 3, 4, 5])

In [71]:
c2

array([[6, 6, 6],
       [3, 4, 5]])

In [72]:
py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [73]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [77]:
f = np.random.random((3,2))

In [78]:
f

array([[0.51842645, 0.03702956],
       [0.8194866 , 0.57452751],
       [0.82482788, 0.52924749]])

In [80]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [82]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [83]:
np.random.seed(123)
np.random.randint(1,10)

3

In [84]:
np.random.seed(123)
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [85]:
np.random.seed(123)
np.random.randint(1,10,(4,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2],
       [1, 1, 4]])

In [86]:
np.zeros(3)

array([0., 0., 0.])

In [88]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.ones(2)

array([1., 1.])

In [91]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
np.full(3,3.14)

array([3.14, 3.14, 3.14])

In [94]:
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [95]:
np.nan

nan

In [96]:
np.array([1,2,np.nan])

array([ 1.,  2., nan])

In [97]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [98]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [99]:
l=np.array([2,2,6,1,3])
np.diff(l)

array([ 0,  4, -5,  2])

In [100]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [102]:
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [103]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [104]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [105]:
np.concatenate([b,b1], axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [106]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [107]:
b2 = np.array([30,60,45])
b2

array([30, 60, 45])

In [108]:
b3 = np.vstack([b,b2])

In [109]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [110]:
first, second = np.hsplit(b3,[2])

In [111]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [112]:
second

array([[ 8],
       [ 8],
       [45]])

In [113]:
first1, second1 = np.vsplit(b3,[2])

In [114]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [116]:
second1

array([[30, 60, 45]])

In [117]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [119]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [120]:
a

array([1, 5, 4])

In [121]:
a[np.newaxis,:]

array([[1, 5, 4]])

In [123]:
a[:,np.newaxis]

array([[1],
       [5],
       [4]])

In [124]:
m=np.arange(0,4)
m

array([0, 1, 2, 3])

In [125]:
n = np.arange(4,7)

In [126]:
n

array([4, 5, 6])

In [127]:
xx, yy = np.meshgrid(m,n)

In [128]:
m

array([0, 1, 2, 3])

In [129]:
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [130]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])